class Offense {
  List<String> offensesList = [
    'Zu spät\nTraining',
    'Zu spät\nTraining mehr als 10 Minuten',
    'Zu spät\nSpiel',
    'Zu spät\nSpiel mehr als 10 Minuten',
    'Unentschuldigtes Fehlen\nTraining',
    'Unentschuldigtes Fehlen\nSpiel',
    'Unentschuldigtes Fehlen\nAbstreuen lt. Plan',
    'Sitzung\nzu spät',
    'Sitzung\nHandy klingelt/vibriert',
    'Spiel\nkein Aufwärmshirt',
    'Spiel\nkeine vollständige Präsentationskleidung (vor und nach Spiel)',
    'Spiel\ngelbe Karte Unsportlichkeit',
    'Spiel\ngelb-rote Karte Unsportlichkeit',
    'Spiel\nrote Karte Unsportlichkeit',
    'Eckle\nTunnel',
    'Eckle\n40 Kontakte',
    'Sonstige\nfurzen Kabine/Dusche',
    'Sonstige\nrauchen im Trikot',
    'Sonstige\nBier trinken im Trikot',
    'Sonstige\nin falsche Whatsapp-Gruppe\nschreiben',
    'Sonstige\nZeitungsbild (im Trikot u. Gesicht erkennbar)',
    'Sonstige\nTrikots nicht bzw. in falschen Wäschesack',
    'Sonstige\nPro Vergehen, dass lt. Trainer alle bestraft werden (z.B. abkürzen)',
    'Sonstige\nNach Auswechslung ungeduscht an Spielerbank rauchen',
    'Sonstige\nVater werden/Hochzeit/Geburtstag',
    'Frischlinge\nEinstand',
    'Frischlinge\nerstes Tor',
    'Frischlinge\nerstes Mal Kapitän',
  ];
}
