import 'album.dart';

class AlbumList {
  List<Album> albumList = [
    Album(
      albumName: 'Album 1',
      albumCoverPath: 'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic1.jpg',
      picturePaths: [
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic1.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic2.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic3.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic4.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic5.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic6.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic7.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic8.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic9.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic10.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic11.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic12.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic13.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic14.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic15.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic16.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic17.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic18.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic19.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic21.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic22.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic23.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic24.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic25.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic26.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic27.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic28.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic29.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic30.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic41.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic42.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic43.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic44.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic45.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic46.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic47.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic48.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic49.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic50.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic61.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic62.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic63.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic64.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic65.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic66.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic67.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic68.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic69.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic70.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic71.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic72.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic73.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic74.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic75.jpg',
        'gs://sgm-duguwe.appspot.com/Galerie/Album/Album 1/pic76.jpg',
      ],
    ),
  ];
}
