class Offense {
  List<String> offensesList = [
    'Zu spät: Training',
    'Zu spät: Training mehr als 10 Minuten',
    'Zu spät: Spiel',
    'Zu spät: Spiel mehr als 10 Minuten',
    'Unentschuldigtes Fehlen: Training',
    'Unentschuldigtes Fehlen: Spiel',
    'Unentschuldigtes Fehlen: Abstreuen lt. Plan',
    'Sitzung: Zu spät',
    'Sitzung: Handy klingelt/vibriert',
    'Spiel: kein Aufwärmshirt',
    'Spiel: keine vollständige Präsentationskleidung (vor und nach Spiel)',
    'Spiel: gelbe Karte Unsportlichkeit',
    'Spiel: gelb-rote Karte Unsportlichkeit',
    'Spiel: rote Karte Unsportlichkeit',
    'Eckle: Tunnel',
    'Eckle: 40 Kontakte',
    'Sonstige: furzen Kabine/Dusche',
    'Sonstige: rauchen im Trikot',
    'Sonstige: Bier trinken im Trikot',
    'Sonstige: in falsche Whatsapp-Gruppe schreiben',
    'Sonstige: Zeitungsbild (im Trikot u. Gesicht erkennbar)',
    'Sonstige: Trikots nicht bzw. in falschen Wäschesack',
    'Sonstige: Pro Vergehen, dass lt. Trainer alle bestraft werden (z.B. abkürzen)',
    'Sonstige: Nach Auswechslung ungeduscht an Spielerbank rauchen',
    'Sonstige: Vater werden/Hochzeit/Geburtstag',
    'Frischlinge: Einstand',
    'Frischlinge: Erstes Tor',
    'Frischlinge: Erstes Mal Kapitän',
  ];
}
